# -*- coding: utf-8 -*-
"""ML_Practical-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDN9IlCGbHEvHy2L-Ttb8uLeUvq6sUR-
"""

# Gradient Descent from Scratch - CGPA Regression

import numpy as np
import matplotlib.pyplot as plt

# Dataset
# Study hours per day
X = np.array([1, 2, 3, 4, 5, 6], dtype=float)

# CGPA
y = np.array([5.5, 6.0, 6.5, 7.2, 7.8, 8.5], dtype=float)

# Initialize parameters
m = 0.0
c = 0.0

# Learning rate
learning_rate = 0.01

# Number of iterations
iterations = 1000

n = len(X)

# Gradient Descent
for i in range(iterations):

    # Predictions
    y_pred = m * X + c

    # Calculate gradients
    dm = (-2 / n) * np.sum(X * (y - y_pred))
    dc = (-2 / n) * np.sum(y - y_pred)

    # Update parameters
    m = m - learning_rate * dm
    c = c - learning_rate * dc

# Final predictions
y_pred = m * X + c

# Calculate Mean Squared Error
mse = np.mean((y - y_pred) ** 2)

print("Final slope (m):", m)
print("Final intercept (c):", c)
print("Mean Squared Error:", mse)

# Predict CGPA for 7 study hours
hours = 7
predicted_cgpa = m * hours + c

print("\nStudy Hours:", hours)
print("Predicted CGPA:", predicted_cgpa)

# Plot actual data
plt.scatter(X, y, label="Actual Data")

# Regression line
plt.plot(X, y_pred, label="Regression Line")

plt.xlabel("Study Hours")
plt.ylabel("CGPA")
plt.title("CGPA Prediction using Gradient Descent")
plt.legend()
plt.show()

# Simple Gradient Descent Example

import matplotlib.pyplot as plt

# Starting value
x = 10.0

# Learning rate
learning_rate = 0.1

# Number of iterations
iterations = 50

# Store values for plotting
x_values = []

# Gradient Descent
for i in range(iterations):

    # Store current x
    x_values.append(x)

    # Function:
    # f(x) = x^2
    #
    # Derivative:
    # f'(x) = 2x
    gradient = 2 * x

    # Update x
    x = x - learning_rate * gradient

print("Initial x = 10")
print("Final x =", x)
print("Minimum value of f(x) =", x ** 2)

# Plot convergence
plt.plot(x_values)

plt.xlabel("Iteration")
plt.ylabel("x value")
plt.title("Gradient Descent Convergence")
plt.show()