# -*- coding: utf-8 -*-
"""ML_Practical-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sgfclQE7g4s0UOSp7kFaX2y3GWArUAU
"""

# K-Nearest Neighbors Classification

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create KNN model
k = 3

model = KNeighborsClassifier(n_neighbors=k)

# Train the model
model.fit(X_train, y_train)

# Predict test data
y_pred = model.predict(X_test)

# Display predictions
print("Actual values:")
print(y_test)

print("\nPredicted values:")
print(y_pred)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Predict a new flower
new_flower = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(new_flower)

print("\nNew Flower Prediction:")
print(iris.target_names[prediction[0]])

# Finding the Best K in KNN

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Store K values and accuracies
k_values = []
accuracies = []

# Test K values from 1 to 15
for k in range(1, 16):

    model = KNeighborsClassifier(
        n_neighbors=k
    )

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    k_values.append(k)
    accuracies.append(accuracy)

    print(
        "K =", k,
        "Accuracy =", round(accuracy, 3)
    )

# Find best K
best_index = accuracies.index(
    max(accuracies)
)

best_k = k_values[best_index]
best_accuracy = accuracies[best_index]

print("\nBest K:", best_k)
print("Best Accuracy:", best_accuracy)

# Plot K vs Accuracy
plt.plot(
    k_values,
    accuracies,
    marker="o"
)

plt.xlabel("K Value")
plt.ylabel("Accuracy")
plt.title("KNN: K Value vs Accuracy")

plt.xticks(k_values)

plt.show()