# -*- coding: utf-8 -*-
"""ML_Practical-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYva2_-Z-jJ3iNAL24jZNFGZCAYj4CPC
"""

# Ridge, Lasso and Elastic Net Regularisation

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

# Dataset
X = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8],
    [7, 8, 9],
    [8, 9, 10],
    [9, 10, 11],
    [10, 11, 12]
])

# Target values
y = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create models
ridge = Ridge(alpha=1.0)
lasso = Lasso(alpha=0.1)
elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)

# Train models
ridge.fit(X_train, y_train)
lasso.fit(X_train, y_train)
elastic.fit(X_train, y_train)

# Predictions
ridge_pred = ridge.predict(X_test)
lasso_pred = lasso.predict(X_test)
elastic_pred = elastic.predict(X_test)

# Print coefficients
print("Ridge Coefficients:")
print(ridge.coef_)

print("\nLasso Coefficients:")
print(lasso.coef_)

print("\nElastic Net Coefficients:")
print(elastic.coef_)

# Calculate MSE
print("\nMean Squared Error:")

print("Ridge:",
      mean_squared_error(y_test, ridge_pred))

print("Lasso:",
      mean_squared_error(y_test, lasso_pred))

print("Elastic Net:",
      mean_squared_error(y_test, elastic_pred))

# R2 scores
print("\nR2 Scores:")

print("Ridge:",
      r2_score(y_test, ridge_pred))

print("Lasso:",
      r2_score(y_test, lasso_pred))

print("Elastic Net:",
      r2_score(y_test, elastic_pred))

# Simple Regularisation Example

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso, ElasticNet

# Simple dataset
X = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12],
    [5, 10, 15],
    [6, 12, 18]
])

y = np.array([10, 20, 30, 40, 50, 60])

# Ordinary Linear Regression
linear = LinearRegression()
linear.fit(X, y)

# Ridge Regression
ridge = Ridge(alpha=1)
ridge.fit(X, y)

# Lasso Regression
lasso = Lasso(alpha=0.1)
lasso.fit(X, y)

# Elastic Net
elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic.fit(X, y)

# Display coefficients
print("Linear Regression Coefficients:")
print(linear.coef_)

print("\nRidge Coefficients:")
print(ridge.coef_)

print("\nLasso Coefficients:")
print(lasso.coef_)

print("\nElastic Net Coefficients:")
print(elastic.coef_)

# Predict a new value
new_data = [[7, 14, 21]]

print("\nPrediction for new data:")

print("Linear Regression:",
      linear.predict(new_data)[0])

print("Ridge:",
      ridge.predict(new_data)[0])

print("Lasso:",
      lasso.predict(new_data)[0])

print("Elastic Net:",
      elastic.predict(new_data)[0])