# -*- coding: utf-8 -*-
"""ML_Practical-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197y6EcOKx3kYXv2b5-BrVl4A1HFI8o0B
"""

# Decision Tree using Gini Index and Entropy

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Decision Tree using Gini Index
gini_tree = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

gini_tree.fit(X_train, y_train)

# Prediction
gini_pred = gini_tree.predict(X_test)

# Accuracy
gini_accuracy = accuracy_score(y_test, gini_pred)

print("Decision Tree using Gini Index")
print("Accuracy:", gini_accuracy)


# Decision Tree using Entropy
entropy_tree = DecisionTreeClassifier(
    criterion="entropy",
    random_state=42
)

entropy_tree.fit(X_train, y_train)

# Prediction
entropy_pred = entropy_tree.predict(X_test)

# Accuracy
entropy_accuracy = accuracy_score(y_test, entropy_pred)

print("\nDecision Tree using Entropy")
print("Accuracy:", entropy_accuracy)

# CCP Pruning and Depth Sweep

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Decision Tree Depth Sweep\n")

# Try different tree depths
for depth in range(1, 8):

    tree = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    tree.fit(X_train, y_train)

    train_accuracy = tree.score(X_train, y_train)
    test_accuracy = tree.score(X_test, y_test)

    print(
        "Depth:", depth,
        "Train Accuracy:", round(train_accuracy, 3),
        "Test Accuracy:", round(test_accuracy, 3)
    )


# -------------------------------
# Cost Complexity Pruning
# -------------------------------

# Create an initial tree
tree = DecisionTreeClassifier(
    random_state=42
)

tree.fit(X_train, y_train)

# Get pruning path
path = tree.cost_complexity_pruning_path(
    X_train,
    y_train
)

ccp_alphas = path.ccp_alphas

print("\nNumber of CCP alpha values:",
      len(ccp_alphas))

# Try different alpha values
best_accuracy = 0
best_alpha = 0

for alpha in ccp_alphas:

    pruned_tree = DecisionTreeClassifier(
        ccp_alpha=alpha,
        random_state=42
    )

    pruned_tree.fit(X_train, y_train)

    prediction = pruned_tree.predict(X_test)

    accuracy = accuracy_score(
        y_test,
        prediction
    )

    print(
        "Alpha:", round(alpha, 4),
        "Accuracy:", round(accuracy, 3)
    )

    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_alpha = alpha


print("\nBest CCP Alpha:", best_alpha)
print("Best Test Accuracy:", best_accuracy)