# -*- coding: utf-8 -*-
"""ML_Practical-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Em4ilaQWM-gLNGa_ykJkPzHYa-PjQq_c
"""

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Check library versions
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

# Create a sample dataset
data = {
    "Name": ["Ananya", "Kumar", "Arjun", "Priya", "Sneha"],
    "Age": [20, 21, 19, 22, 20],
    "CGPA": [9.2, 8.5, 9.0, 7.8, 8.9],
    "Department": ["IT", "ECE", "CSE", "IT", "CSE"]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Display dataset
print("\nDataset:")
print(df)

# Display first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# Display dataset information
print("\nDataset Information:")
print(df.info())

# Display statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Display column names
print("\nColumn Names:")
print(df.columns)

# Display shape
print("\nDataset Shape:")
print(df.shape)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris dataset
df = sns.load_dataset("iris")

# Display complete dataset
print("Iris Dataset:")
print(df)

# Display first 5 rows
print("\nFirst 5 rows:")
print(df.head())

# Display last 5 rows
print("\nLast 5 rows:")
print(df.tail())

# Display number of rows and columns
print("\nDataset Shape:")
print(df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns)

# Display data types
print("\nData Types:")
print(df.dtypes)

# Display statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Count different species
print("\nSpecies Count:")
print(df["species"].value_counts())

# Visualize species distribution
sns.countplot(x="species", data=df)
plt.title("Iris Species Distribution")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()
