# -*- coding: utf-8 -*-
"""ML_Practical-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztv80pZrfs7k-USCqm_4-3UMJ0Ndrq3q
"""

# Binary Logistic Regression

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

# Dataset
# Study hours
X = np.array([[1], [2], [3], [4], [5], [6], [7], [8]])

# 0 = Fail, 1 = Pass
y = np.array([0, 0, 0, 1, 1, 1, 1, 1])

# Create Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(X, y)

# Predictions
predictions = model.predict(X)

print("Actual values:")
print(y)

print("\nPredicted values:")
print(predictions)

# Predict for new students
new_hours = np.array([[2.5], [5.5], [7.5]])

new_predictions = model.predict(new_hours)

print("\nPredictions for new students:")

for hours, prediction in zip(new_hours, new_predictions):
    if prediction == 1:
        print(hours[0], "hours -> Pass")
    else:
        print(hours[0], "hours -> Fail")

# Accuracy
accuracy = model.score(X, y)

print("\nAccuracy:", accuracy)

# Plot
plt.scatter(X, y)

plt.xlabel("Study Hours")
plt.ylabel("Pass / Fail")
plt.title("Binary Logistic Regression")

plt.show()

# Multinomial Logistic Regression

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load Iris dataset
iris = sns.load_dataset("iris")

# Features
X = iris[
    ["sepal_length", "sepal_width",
     "petal_length", "petal_width"]
]

# Target
y = iris["species"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create multinomial Logistic Regression model
model = LogisticRegression(
    max_iter=200
)

# Train model
model.fit(X_train, y_train)

# Predict test data
y_pred = model.predict(X_test)

# Display predictions
print("Actual values:")
print(y_test.values)

print("\nPredicted values:")
print(y_pred)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Predict a new flower
new_flower = [[5.1, 3.5, 1.4, 0.2]]

prediction = model.predict(new_flower)

print("\nNew Flower Prediction:")
print(prediction[0])

# Plot
sns.scatterplot(
    x="petal_length",
    y="petal_width",
    hue="species",
    data=iris
)

plt.title("Multinomial Logistic Regression Dataset")
plt.show()