# -*- coding: utf-8 -*-
"""ML_Practical-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmZ8sZ1Sy5iEDEoUmloCyuNAE95zZWwH
"""

# Exploratory Data Analysis and Visualization

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Iris dataset
df = sns.load_dataset("iris")

# Display dataset
print("Dataset:")
print(df.head())

# Basic information
print("\nDataset Information:")
print(df.info())

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nNumber of Duplicate Rows:")
print(df.duplicated().sum())

# Species count
print("\nSpecies Count:")
print(df["species"].value_counts())

# Histogram
df.hist(figsize=(10, 8))
plt.suptitle("Distribution of Iris Features")
plt.show()

# Scatter plot
sns.scatterplot(
    x="sepal_length",
    y="sepal_width",
    hue="species",
    data=df
)

plt.title("Sepal Length vs Sepal Width")
plt.show()

# Box plot
sns.boxplot(
    x="species",
    y="petal_length",
    data=df
)

plt.title("Petal Length by Species")
plt.show()

# Correlation heatmap
numeric_df = df.select_dtypes(include="number")

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

# EDA using Student Dataset

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create student dataset
data = {
    "Student": ["Ananya", "Rahul", "Priya", "Arjun", "Sneha",
                "Kiran", "Varun", "Divya"],

    "Maths": [90, 75, 88, 65, 95, 72, 80, 85],

    "Python": [92, 78, 85, 70, 96, 75, 82, 88],

    "Attendance": [95, 82, 90, 70, 98, 80, 85, 92]
}

df = pd.DataFrame(data)

# Display dataset
print("Student Dataset:")
print(df)

# Dataset information
print("\nDataset Information:")
print(df.info())

# Statistical summary
print("\nStatistical Summary:")
print(df.describe())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Calculate average marks
df["Average"] = (df["Maths"] + df["Python"]) / 2

print("\nAverage Marks:")
print(df[["Student", "Average"]])

# Bar graph
plt.figure(figsize=(8, 5))

plt.bar(df["Student"], df["Average"])

plt.title("Average Marks of Students")
plt.xlabel("Student")
plt.ylabel("Average Marks")

plt.xticks(rotation=45)
plt.show()

# Scatter plot
plt.figure(figsize=(7, 5))

sns.scatterplot(
    x="Attendance",
    y="Average",
    data=df
)

plt.title("Attendance vs Average Marks")
plt.xlabel("Attendance (%)")
plt.ylabel("Average Marks")

plt.show()

# Correlation heatmap
plt.figure(figsize=(7, 5))

sns.heatmap(
    df[["Maths", "Python", "Attendance", "Average"]].corr(),
    annot=True
)

plt.title("Correlation Between Student Features")
plt.show()