# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DA-xLej-V5Sapcg0le873OwyJctd_DAi
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Customer dataset
# X = Income in lakhs
# Y = Spending Score

X = np.array([
    [2, 20],
    [2.5, 25],
    [3, 30],
    [8, 80],
    [8.5, 85],
    [9, 90]
])

# Create K-Means model
kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

# Train the model
kmeans.fit(X)

# Get cluster labels
labels = kmeans.labels_

# Print cluster labels
print("Cluster Labels:")
print(labels)

# Print centroids
print("\nCentroids:")
print(kmeans.cluster_centers_)

# Plot the clusters
plt.scatter(
    X[:, 0],
    X[:, 1],
    c=labels,
    s=100
)

# Plot centroids
plt.scatter(
    kmeans.cluster_centers_[:, 0],
    kmeans.cluster_centers_[:, 1],
    marker='X',
    s=200
)

plt.xlabel("Annual Income (₹ Lakhs)")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation using K-Means")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN

# Dataset
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [10, 11],
    [11, 12],
    [12, 13],
    [50, 50]
])

# Create DBSCAN model
dbscan = DBSCAN(eps=2, min_samples=2)

# Train the model
dbscan.fit(X)

# Get cluster labels
labels = dbscan.labels_

# Print results
print("Cluster Labels:")
print(labels)

# Plot clusters
plt.scatter(X[:, 0], X[:, 1], c=labels, s=100)

plt.xlabel("X")
plt.ylabel("Y")
plt.title("DBSCAN Clustering")
plt.show()